### ISSUE TITLE
An error occurred while Primer/TestSelector cop was inspecting component.rb

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1810]
Started seeing this error with version 0.0.120.

The offending lines that rubocop alerts are using a `render(Primer::Beta::Button.new....` or `render Primer::Box.new(` on the component.

Environment
```
Rubocop 1.44.1 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.1.2) [x86_64-darwin21]
```

Stack trace:
```
An error occurred while Primer/TestSelector cop was inspecting component.rb:34:11.
undefined method `value' for s(:dsym,
  s(:begin,
    s(:send, nil, :identifier)),
  s(:str, "-target")):RuboCop::AST::Node

            pair.key.value == :"test-selector" || pair.key.value == "test-selector"
                    ^^^^^^
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/primer_view_components-0.0.120/lib/rubocop/cop/primer/test_selector.rb:39:in `block in on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/primer_view_components-0.0.120/lib/rubocop/cop/primer/test_selector.rb:38:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/primer_view_components-0.0.120/lib/rubocop/cop/primer/test_selector.rb:38:in `find'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/primer_view_components-0.0.120/lib/rubocop/cop/primer/test_selector.rb:38:in `on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:101:in `public_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:101:in `block (2 levels) in trigger_responding_cops'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:165:in `with_cop_error_handling'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:100:in `block in trigger_responding_cops'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:99:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:99:in `trigger_responding_cops'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:156:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:156:in `on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:154:in `on_block'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:154:in `on_def'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:154:in `on_class'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.1/lib/rubocop/ast/traversal.rb:20:in `walk'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/team.rb:154:in `investigate_partial'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cop/team.rb:97:in `investigate'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:322:in `inspect_file'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:266:in `block in do_inspection_loop'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:300:in `block in iterate_until_no_changes'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:293:in `loop'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:293:in `iterate_until_no_changes'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:262:in `do_inspection_loop'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:143:in `block in file_offenses'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:168:in `file_offense_cache'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:142:in `file_offenses'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:78:in `block in warm_cache'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:238:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:78:in `warm_cache'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/runner.rb:51:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/command.rb:11:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli/environment.rb:18:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli.rb:72:in `run_command'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli.rb:79:in `execute_runners'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/lib/rubocop/cli.rb:48:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/exe/rubocop:19:in `block in <top (required)>'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/benchmark-0.2.1/lib/benchmark.rb:311:in `realtime'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.44.1/exe/rubocop:19:in `<top (required)>'
/installs/ruby/3.1.2/bin/rubocop:25:in `load'
/installs/ruby/3.1.2/bin/rubocop:25:in `<main>'
```

**Comment by danielnc** [comment]
I am also having the same issue, which is preventing us from properly using erblint/rubocop

any idea on how to fix this?

**Comment by lesliecdubs** [comment]
👋 @danielnc or @raivil, are either of you able to point us to a code sample or repo where the cop is failing?

**Comment by danielnc** [comment]
@lesliecdubs here is one of the erb template files that is triggering this error

```
<%= turbo_frame_tag :infinite_pagination do %>
  <%= render(Primer::Box.new(data: { controller: identifier, "#{identifier}-target": "paginationContainer" }, classes: class_for(:wrapper))) do %>
    <%= render(Primer::Beta::Spinner.new(size: :small, data: { "#{identifier}-target": "spinner" })) %>
    <%== pagy_nav_js(results) %>
  <% end %>
<% end %>
```
