### ISSUE TITLE
primer_text_field.ts:18 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by raivil** [primer/view_components#1929]
One simple form started to raise this error on console when upgrading from `0.0.121` to `0.1.4`.
Wasn't able to figure out the cause yet. 

```
primer_text_field.ts:18 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at PrimerTextFieldElement.connectedCallback (primer_text_field.ts:18:23)
    at Ht.connectedCallback (core.js:44:28)
    at Ht.t.connectedCallback (core.js:12:22)
connectedCallback	@	primer_text_field.ts:18
connectedCallback	@	core.js:44
Ht.t.connectedCallback	@	core.js:12
```

Form is quite simple:
```
class Devise::SessionForm < ApplicationForm
  form do |session_form|
    session_form.text_field(
      name: :email,
      label: I18n.t("activerecord.attributes.user.email"),
      required: true,
      autofocus: true,
      autocomplete: "email",
      type: "email"
    )

    session_form.text_field(
      name: :password,
      label: I18n.t("activerecord.attributes.user.password"),
      required: true,
      autocomplete: "current-password",
      type: "password"
    )
end
```

**Comment by camertron** [comment]
Hey @raivil, I'm struggling to reproduce this. It would be super helpful if you could put together a demo repo showcasing the issue.

**Comment by camertron** [comment]
I'm going to close this for now since there has been no activity for a while and I am unable to reproduce the issue. @raivil, please feel free to reopen if you're still experiencing the bug.

**Comment by nsimmons** [comment]
In case it's helpful, I was running into this same issue and fixed it by moving the `primer_view_components` javascript tag from the head to the end of the body.
