### ISSUE TITLE
flex component story is crashing

### ISSUE THREAD

**Issue by srt32** [primer/view_components#207]
```
torybook | [./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main}
storybook | [./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main}
storybook | [./node_modules/@storybook/core/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main}
storybook | [./node_modules/@storybook/server/dist/client/index.js] 1.21 KiB {vendors~main}
storybook | [./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main}
storybook | [./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main}
storybook | [./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] 7.68 KiB {vendors~main}
storybook |     + 716 hidden modules
storybook |
storybook | WARNING in ../stories/primer/flex_component.stories.json
storybook | Module build failed (from ./node_modules/@storybook/server/dist/server/loader.js):
storybook | TypeError: Cannot convert undefined or null to object
storybook |     at Function.keys (<anonymous>)
storybook |     at stringifyObject (/Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:130:16)
storybook |     at /Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:120:14
storybook |     at Array.map (<anonymous>)
storybook |     at stringifyObject (/Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:119:31)
storybook |     at /Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
storybook |     at Array.map (<anonymous>)
storybook |     at stringifyObject (/Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
storybook |     at /Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
storybook |     at Array.map (<anonymous>)
storybook |     at stringifyObject (/Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
storybook |     at /Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
storybook |     at Array.map (<anonymous>)
storybook |     at stringifyObject (/Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
storybook |     at /Users/srt32/src/github.com/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:181:73
storybook |     at Array.forEach (<anonymous>)
storybook |  @ \.)(?=.)[^/]*?\.stories\.json)$ (/Users/srt32/src/github.com/primer/view_components sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.json)$) ./stories/primer/flex_component.stories.json
storybook |  @ ./.storybook/generated-stories-entry.js
```

**Comment by joelhawksley** [comment]
@srt32 do you think we could add the storybook generation script to CI so the build will fail if it's broken?

**Comment by srt32** [comment]
@manuelpuyol do we have any prior art on building storybook (installing deps and what not) on CI?
