### ISSUE TITLE
flaky build failures on bundle

### ISSUE THREAD

**Issue by srt32** [primer/view_components#213]
Things resolve on rebuild and errors tend to look like this:

```
## Backtrace

NoMethodError: undefined method `name' for "Gemfile":String
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/resolver/spec_group.rb:65:in `eql?'
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:607:in `block in create_conflict'
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:606:in `each'
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:606:in `create_conflict'
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
  /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
```

**Comment by manuelpuyol** [comment]
Looks like https://github.com/primer/view_components/pull/216 solved this!
