### ISSUE TITLE
LoadError: no such file to load -- helpers/primer/form_helper

### ISSUE THREAD

**Issue by agardiner** [primer/view_components#2359]
With the 0.13.2 version of the primer_view_components gem, I get a LoadError on first access of any page of my app:
```
Puma caught this error: no such file to load -- helpers/primer/form_helper (LoadError)
org/jruby/RubyKernel.java:1071:in 'require'
.../lib/ruby/gems/shared/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in 'require'
.../lib/ruby/gems/shared/gems/primer_view_components-0.13.2/lib/primer/view_components/engine.rb:47:in 'block in Engine'
```

The error is due to a require that uses an incorrect path to the form_helper.
```
      initializer "primer.forms.helpers" do
        ActiveSupport.on_load :action_controller_base do
 --->     require "helpers/primer/form_helper"
          helper Primer::FormHelper

          # make primer_form_with available to view components also
          ViewComponent::Base.prepend(Primer::FormHelper)
        end
      end
```

The correct helpers folder location is actually added to the eager_load_paths earlier in the engire:
```
      config.eager_load_paths = %W[
        #{root}/app/components
        #{root}/app/forms
        #{root}/app/helpers
        #{root}/app/lib
      ]
```

Therefore, simply removing the require on line 47 fixes the issue.

**Comment by safeforge** [comment]
Fixed by https://github.com/primer/view_components/pull/2336
