### ISSUE TITLE
SassC::SyntaxError during Rails asset precompilation

### ISSUE THREAD

**Issue by ksy90101** [primer/view_components#2967]
I am encountering a `SassC::SyntaxError` during the Rails asset precompilation step. The error seems to be related to the `@supports` rule in my CSS.

**Error Message:**
```
SassC::SyntaxError: Error: Invalid CSS after "...}@supports not ": expected @supports condition (e.g. (display: flexbox)), was "selector(:popover-o"
```

**Error Trace:**
```
#14 6.005 SassC::SyntaxError: Error: Invalid CSS after "...}@supports not ": expected @supports condition (e.g. (display: flexbox)), was "selector(:popover-o"
#14 6.005         on line 32:124424 of stdin
#14 6.005 >> erflow:hidden;visibility:hidden}@supports not selector(:popover-open){[popov
#14 6.005    ------------------------------------------^
#14 6.005 stdin:32
#14 6.005 /usr/local/bundle/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
#14 6.005 /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails/compressor.rb:29:in `call'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/sass_compressor.rb:30:in `call'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:32:in `block in call'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:31:in `call'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/base.rb:81:in `find_asset'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/base.rb:88:in `find_all_linked_assets'
#14 6.005 /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
#14 6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
#14 6.005 Tasks: TOP => assets:precompile
#14 6.005 (See full trace by running task with --trace)
#14 ERROR: process "/bin/sh -c bundle exec rake assets:precompile" did not complete successfully: exit code: 1
------
 > [prd 4/4] RUN bundle exec rake assets:precompile:
6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
6.005 /usr/local/bundle/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
6.005 /usr/local/bundle/g

**Comment by camertron** [comment]
Hey @ksy90101, thanks for reaching out about this. We don't currently support using sassc and sassc-rails with primer_view_components. Please consider using postcss or dartsass-rails instead, or use the precompiled version of our CSS styles. Here's our getting started guide for CSS bundlers: https://primer.style/guides/rails#css-bundlers

**Comment by ksy90101** [comment]
@camertron 
I wrote the issue and changed it to `dartsass-rails`. After the change, I confirmed that it works correctly. Thank you for your help
