### ISSUE TITLE
Handle `nil` cases in storybook

### ISSUE THREAD

**Issue by natashaU** [primer/view_components#90]
While working on the label component: https://github.com/primer/view_components/blob/main/app/components/primer/label_component.rb

I noticed that there was an error when implementing introducing a storybook story. '

The label component has the following:

```
SCHEME_MAPPINGS = {
      # gray
      gray: "Label--gray",
      dark_gray: "Label--gray-darker",

      # colored
      yellow: "Label--yellow",
      orange: "Label--orange",
      red: "Label--red",
      green: "Label--green",
      blue: "Label--blue",
      purple: "Label--purple",
      pink: "Label--pink",

      # Deprecated
      outline: "Label--outline",
      green_outline: "Label--outline-green",
    }.freeze
    SCHEME_OPTIONS = SCHEME_MAPPINGS.keys << nil
```

However, the following code in the story is unable to handle nil cases:
`select(:scheme, Primer::StoriesHelper.array_to_options(Primer::LabelComponent::SCHEME_MAPPINGS.keys), :blue)`

That's because nil shows up as ` :nil ` a hash without a key. 

cc/  @joelhawksley @aellispierce @jonspalmer

**Comment by jonspalmer** [comment]
IMO we should just be using arrays as the options. https://github.com/jonspalmer/view_component_storybook supports this as of version 0.5.0 and eliminates the need for `Primer::StoriesHelper.array_to_options`

**Comment by manuelpuyol** [comment]
as soon as https://github.com/primer/view_components/pull/89 merges I'll update stories definitions :)

**Comment by manuelpuyol** [comment]
@jonspalmer arrays with `nil` as an option won't work

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stringifyObject (/Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:130:16)
    at /Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:120:14
    at Array.map (<anonymous>)
    at stringifyObject (/Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:119:31)
    at /Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
    at Array.map (<anonymous>)
    at stringifyObject (/Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
    at /Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
    at Array.map (<anonymous>)
    at stringifyObject (/Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
    at /Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:132:21
    at Array.map (<anonymous>)
    at stringifyObject (/Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:131:47)
    at /Users/manuelpuyol/primer/view_components/demo/node_modules/@storybook/server/dist/lib/compiler/stringifier.js:181:73
    at Array.forEach (<anonymous>)
```

any ideas on how to proceed?

**Comment by jonspalmer** [comment]
@manuelpuyol I'm not sure if Storybook supports null in this way. Playing around with it adding null or undefined to a Storybook Options control gets converted to a string (which is probably fair) for Controls. I think that means over the wire the value will be "null". I guess view_component_storybook could convert "null" to nil in the options case. Thoughts?

**Comment by manuelpuyol** [comment]
I think converting to `"null"` for storybook and converting back to `nil` could be a good idea :)

**Comment by natashaU** [comment]
FYI --- this same issue came up again as I was writing the storybook story for the flex component[app/components/primer/flex_component.rb], see a snippet of the code below:

```
JUSTIFY_CONTENT_DEFAULT = nil
    JUSTIFY_CONTENT_MAPPINGS = {
      flex_start: "flex-justify-start",
      flex_end: "flex-justify-end",
      center: "flex-justify-center",
      space_between: "flex-justify-between",
      space_around: "flex-justify-around",
    }
    JUSTIFY_CONTENT_OPTIONS = [JUSTIFY_CONTENT_DEFAULT, *JUSTIFY_CONTENT_MAPPINGS.keys]
```

as @manuelpuyol outlined above, arrays with nil as an option won't work and the recent addition of converting null to nil still did not prevent a `TypeError: Cannot convert undefined or null to object`error. This is because JUSTIFY_CONTENT_DEFAULT is nil and 

The same issue pops up when we have a default option of an empty string in the popover component [app/components/primer/popover_component.rb]. @cheshire137 came up with a creative solution to write a story by subtracting the default option in the popover component story from the hash (in this case, CARET_DEFAULT is an empty string aka` " "` rather than` nil`)

```
(
    Primer::PopoverComponent::Body::CARET_MAPPINGS.keys -
    [Primer::PopoverComponent::Body::CARET_DEFAULT]
  ).each do |caret|
    story("popover_#{caret}".to_sym) do
```

However, this just removes the default as an option, and ideally, we should be including the default as an option since the actual component has a default option. Perhaps we should come up with a solution to handle the default in all cases that it may be nil / null or an empty string?

cc @joelhawksley @aellispierce
